# https://golangci-lint.run/usage/linters/
linters:
  disable-all: true
  enable:
    # Enabled by default linters:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    # Disabled by default linters:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    # - containedctx
    - contextcheck
    # - cyclop
    - decorder
    - depguard
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - execinquery
    - exhaustive
    # - exhaustruct
    - exportloopref
    - forbidigo
    - forcetypeassert
    # - funlen
    - gci
    - ginkgolinter
    - gocheckcompilerdirectives
    # - gochecknoglobals
    - gochecknoinits
    # - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    # - godox
    # - goerr113
    - gofmt
    - gofumpt
    - goheader
    - goimports
    # - gomnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    # - gosec
    - grouper
    - importas
    - interfacebloat
    # - ireturn
    - loggercheck
    - maintidx
    - makezero
    - misspell
    # - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    # - nlreturn
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    # - paralleltest # TODO: enable
    - prealloc
    - predeclared
    - promlinter
    - reassign
    # - revive # TODO: enable
    # - rowserrcheck
    # - stylecheck # TODO: enable
    - tagliatelle
    - tenv
    - testableexamples
    # - testpackage
    - thelper
    # - tparallel # TODO: enable
    - unconvert
    - unparam
    - usestdlibvars
    # - varnamelen
    # - wastedassign
    - whitespace
    - wrapcheck
    - wsl

  fast: false

issues:
  # Disable the default exclude list so that all excludes are explicitly
  # defined in this file.
  exclude-use-default: false
  # Default: https://golangci-lint.run/usage/false-positives/#default-exclusions
  exclude:
    - "Error return value of .((os\\.)?std(out|err)\\..*|.*Close|.*Flush|os\\.Remove(All)?|.*printf?|os\\.(Un)?Setenv). is not checked"

  exclude-rules:
    - linters: [dupl]
      text: "lines are duplicate of `.+_test.go:.+`"

linters-settings:

  # govet:
  #   check-shadowing: true
  #   enable-all: true
  #   disable:
  #     - fieldalignment
  #     - nilness
  #     - shadow
  #     - unusedwrite
  gofmt:
    simplify: true

  # forbidigo:
  #   exclude_godoc_examples: false

  # depguard:
  #   list-type: denylist
  #   include-go-root: true

run:
  timeout: 5m
  concurrency: 4
  skip-dirs-use-default: false
  skip-dirs:
    - /usr/local/go/src
    - /go/src
